# Generated by Django 4.2.6 on 2023-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listingmodel_delete_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
