# Generated by Django 4.2.6 on 2023-10-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_categorymodel_alter_listingmodel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
