# Generated by Django 4.2.6 on 2023-10-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_delete_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='auctions.listingmodel'),
        ),
    ]
